experiment:
  name: Output image
  description: "The Scream - Edvard Munch image"

data:
  content_path: data/raw/content/house.jpg
  style_path: data/raw/style/the-scream.webp

image:
  size: 256

optimization:
  steps: 1000
  learning_rate: 0.03

loss:
  content_weight: 1.0
  style_weight: 10000000.0
  style_layers:
    conv1: 1.0
    conv2: 0.8
    conv3: 0.6
    conv4: 0.4
    conv5: 0.2

output:
  path: outputs/images/the-scream-result.png